{% set name = "rte_rrtmgp" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/earth-system-radiation/rte-rrtmgp/archive/refs/tags/v{{ version }}.zip
  sha256: b969d8745687de277e29247212a254afef3adcaec19492e580a4541955941542

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - cmake
    - ninja
    - gnuconfig   # [unix]
    - python
  host:
    - python
    - netcdf4
    - xarray
    - dask
    - numpy
    - netcdf-fortran >=4.5,<5.0
  run:
    - python

# Check if the files exists
test:
  commands:
    - test -f $PREFIX/lib/librte{{ SHLIB_EXT }}         # [not win]
    - test -f $PREFIX/lib/librrtmgp{{ SHLIB_EXT }}      # [not win]
    - if not exist "%PREFIX%\bin\librte.dll" exit 1     # [win]
    - if not exist "%PREFIX%\bin\librrtmgp.dll" exit 1  # [win]

about:
  home: https://github.com/earth-system-radiation/rte-rrtmgp
  summary: Fortran codes for computing radiative fluxes in planetary atmospheres.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://earth-system-radiation.github.io/rte-rrtmgp/how-tos/

extra:
  recipe-maintainers:
    - RobertPincus
    - makepath-alex
