# Check if the files exists
schema_version: 1

context:
  name: rte_rrtmgp
  version: "1.9.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/earth-system-radiation/rte-rrtmgp/archive/refs/tags/v${{ version }}.zip
  sha256: b969d8745687de277e29247212a254afef3adcaec19492e580a4541955941542

build:
  number: 2

requirements:
  build:
    - if: not win
      then: 
        - ${{ compiler('cxx') }}
        - ${{ compiler('fortran') }}
        - ${{ stdlib('c') }}
      else: 
        - ${{ compiler('m2w64_fortran') }}
        - ${{ compiler('m2w64_c') }}
        - ${{ stdlib('m2w64_c') }}
    - cmake
    - ninja
    - if: unix
      then: 
        - gnuconfig
    - python
  host:
    - python
    - netcdf4
    - xarray
    - dask
    - numpy
    - netcdf-fortran >=4.5,<5.0
  run:
    - python

tests:
  - package_contents:
      strict: true
      lib: 
        - librte
        - librrtmgp
        
about:
  summary: Fortran codes for computing radiative fluxes in planetary atmospheres.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/earth-system-radiation/rte-rrtmgp
  documentation: https://earth-system-radiation.github.io/rte-rrtmgp/

extra:
  recipe-maintainers:
    - RobertPincus
    - makepath-alex
