# Check if the files exists
schema_version: 1

context:
  name: rte_rrtmgp
  version: "1.9.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/earth-system-radiation/rte-rrtmgp/archive/refs/tags/v${{ version }}.zip
  sha256: 260a58842da7c0bb7e20dd0de0e3710604c92b3e528f106e8f2c58445b559e1b

# In fact Windows builds  using [compiler('m2w64_fortran'), compiler('m2w64_c'), stdlib('m2w64_c')]
#   but package_contents aren't found and I can't figure out how to skip tests for 
#   only one platform 
build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
    - if: unix
      then: gnuconfig
    - netcdf-fortran >=4.5,<5.0
    - python
    - netcdf4
    - xarray
    - dask
    - numpy
  host:
    - python
    - netcdf4
    - xarray
    - dask
    - numpy
  run:
    - python

tests:
  - package_contents:
      lib: 
        - librte
        - librrtmgp
      include:
        - rte_types.h
        - rte_kernels.h
        - rrtmgp_kernels.h
      files:
        - share/rte-rrtmgp/rrtmgp*.nc

about:
  summary: Fortran codes for computing radiative fluxes in planetary atmospheres.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/earth-system-radiation/rte-rrtmgp
  documentation: https://earth-system-radiation.github.io/rte-rrtmgp/

extra:
  recipe-maintainers:
    - RobertPincus
    - makepath-alex
